# Generated by Django 2.2 on 2020-12-01 21:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201128_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 21, 47, 43, 105670, tzinfo=utc)),
        ),
    ]
